# Exam  Policies

## Number of exams 

1. **There will be 3 mini-tests during the semester.**  1 will be dropped as detailed later in the syllabus.
1. **There are approximately 8 lectures and 3 recitations per unit and mini-test.** (Some units may have 3 recitations)


## Exam drops

1. Your lowest scores of the 3 unit exams will be automatically dropped when grades are calculated at the end of the semester.  (Prior to that it will be factored into your grade.)
1. **The final exam CANNOT be dropped.**
1. If you are unable to take a exam for ANY reason it will be counted zero.
1. If you miss just 1 test, that score will be automatically dropped as your lowest score when grades are calculated.
1. Your score on the final can replace your 2nd lowest score, if the final is higher.  See section of the syllabus on the final exam.


If you miss 2 tests, 1 will be dropped and the 2nd can be replaced by your score on the final.

## There are no makeup exams

**No makeup exams** will be given for any reason.


## Exams will be in-person and most likely on Canvas


* All exams, including the final, will be in-person.  
* **Canvas-based exams:** If/when exams are taken using Canvas, it is your responsibility to assure that you have adequate power to your device and internet access.
* If you lose power or internet access before completing the test and receive a sub-optimal score then this score will likely be the test score that gets dropped.

## Exam length & format

NOTE: the following policies are provisional and may be adjusted as needed to optimize test length and how to implement the "buffer question" policy in Canvas.

* Exam will be scored out of 40 points.   However, there will be 41 points worth of questions on the test.
* Each test therefore will contain 1 buffer points that you can miss without harming your grade. 
* The maximum score on an exam will be capped at 40/40 If you get all 41 questions correct your score will be 100%. 
* No extra credit will be offered on tests; the maximum score on a test will be 100%.
 

## Test question formats

* Test questions will frequently be multiple choice.  Keyword: "frequently" - there will other types of questions too.
* Most tests will have more than one question requiring a numeric calculation.  You will be provided scratch paper for the exam.
* Other common forms of questions are fill in the blank, dropdowns, or matching.  This includes multiple fill in the blanks, multiple dropdowns, etc.  
* There will be NO True/False questions on tests.
* For fill in the blank questions spelling errors will result in 0 points.  No partial credit will be given.

## Other exam policies

* When a test occurs on a Thursday, lecture material on Tuesday **WILL** occur on the test unless otherwise stated.
* **Practice exam:** The recitation the Friday before a test will be used to go over a practice exam.
* **I don't answer  any questions during the test.**  This is to preserve a quiet, consistent testing environment for all students.


<!-- * Some multiple-choice questions will likely be "select all correct answers."  For these questions, credit will only be given if you select ALL of the correct answers.  If you select an incorrect answer you will receive 0 points. -->

<!-- calculators -->


