# Office Hours 

## Dr. Brouwer office hours

Office hours will be held Mondays 12:00-1:00 PM and Thursdays from 9:30 to 10:30 PM.  (These are subject to modification once the semester begins)

<!-- Zoom? In person?  -->

A Zoom link will be sent to the class and anyone who has a question or wants to hear the discussion can join. 

Office hours will not be recorded.


**Some guidelines for office hours:**

* Don't be intimidated by office hours.  One of my favorite parts of my job is talking with students one-on-one.
* Be prepared for office hours.  Come with specific questions related to slides, figures, etc.  But if you just want to listen, that's totally cool
* Office hours are for everyone. If multiple people show up I will alternate between them to answer their questions. If I feel I have answered your main questions I may ask that we table our discussion to cover other questions.
* Note: During finals week I do not hold office hours and am not available for appointments.
* During office hours, specific questions are better than vague ones, even if it's just "I specifically don't understand Fig. 4 in this chapter."  A question like "I don't understand natural selection" is harder for me to work with.
* I'm also happy to talk about study strategies, classes you might want to take, research opportunities etc.


## UTA Office Hours

Undergraduate Teaching Assistants (UTAs) will hold office hours throughout the week by in-person and via Zoom. 

These will be finalized by the 2nd week of class and summarized online.

You can attend any UTA's office hours. UTAs will have access to keys to help you review assignments and recitation materials.

UTA's will read the tests but will not have access to test materials.