# Exam review: "Rematches", reviews, re-trys and exam inquiries

<!-- review of all questions at another time? -->

After an exam you will have several opportunities to review the content of the exam. 

<!-- In general, exam questions and the key are NOT released.  You will have the opportunity to review the exams during specific time periods, but like the SAT, MCAT, GRE etc. you do not get the full test returned to you. -->

## Exam rematches

The first recitation after an exam will be used as a time for an "**Exam Rematch**."

During **Exam Rematches**, you will work in small groups to work through the questions on the exam again.  You can discuss answers as a group, though each person will submit their own separate answers.

Exam rematches are graded for correctness, but are separate assignments and do NOT add points back to your score.  They are a tool for review of the material while it is fresh in your memory.

The **Exam Rematch** assignment may contain all questions or the test, or be based just on the most missed and hardest questions of the preceding test. 

## Exam review

After grades are released the most missed questions will be discussed in class.  You can take notes on the questions, but the full text of the questions will not be released at this time.

## Exam release and key

After all steps of the exam review process your individual exams will be released for you to review.  If you have further question about the exam an Exam Inquiry process will be established.  Additional details will be released after the first exam review is over.

<!-- ## Retired questions -->

<!-- After most exams I will "retire" a few questions and release their full text and the key. -->


## Exam Inquiries

If you have an inquiry about a test question you can fill out an Exam Inquiry Form after the key is released.
You will have until the Friday of the week the key is released to complete the form.
I will read all inquiries to determine if any immediate issue needs to be resolved.  Inquiries will then be processed as detailed for Grade Inquiry Forms. 
Unless you submitted an Exam Inquiry Form I will not discuss specific test questions during office hours.