# Grade inquires


* If you are concerned that your grade has be miscalculated, a key was wrong, or that there were multiple correct answers please fill out a Grade Inquiry Form. 
* I will briefly evaluate submitted forms to determine if there is an issue that requires immediate attention.
* Otherwise, the resolution of the issue will not occur until grades are calculated. 
* AFTER final grades have been calculated I will determine if the resolution of issues on Grade Inquiry forms will impact your final grade.
* If your final grade will potentially be impacted I will fully evaluate your inquiry and notify you via email regarding its resolution.
* If you did not receive information about your inquiry it means your final grade would not have been impacted. * All Inquiry forms for recitation related homework or other assignments MUST be received within 48 hours of when the key was released.
* Inquires about exam are due the Friday after a key is released.  See here for more information.
* Inquiries about the final exam will not be addressed until the next semester.



duplicated?
If you are concerned that your grade has be miscalculated, a key was wrong, or that there were multiple correct answers please fill out a Grade Inquiry Form. 
I will briefly evaluate submitted forms to determine if there is an issue that requires immediate attention.  Otherwise, the resolution of the issue will not occur until grades are calculated. 

 AFTER final grades have been calculated I will determine if the resolution of issues on Grade Inquiry forms will impact your final grade.
If your final grade will potentially be impacted I will fully evaluate your inquiry and notify you via email regarding its resolution.
If you did not receive information about your inquiry it means your final grade would not have been impacted. 
All Inquiry forms for recitation related homework or other assignments MUST be received within 48 hours of when the key was released.
Inquires about exam are due the Friday after a key is released.  See here for more information.
Inquiries about the final exam will not be addressed until the next semester.