#  Foundations 1 - things to know {#f1}

The most important concepts from the first semester of Foundations of Biology will be reviewed at least briefly, and in some cases this material will be covered in-depth.  Below is a summary of key things from the textbook covered in Foundations 1 relevant to this course.

Sections or figures relating to concepts that will be covered or reviewed directly in a lecture or some other material are indicated below with a " (F2!)".  Things not starred will be considered general background knowledge that you should be familiar with.  Unless vocab from these sections occurs in a Foundations 2 lecture you will not be expected to have these terms memorized.  If you need help reviewing anything office hours with me and undergraduate UTAs will be available.  

Note: if a figure is _not_ mentioned, it can be ignored.

<!-- If you don’t yet have access yet to the book, many of the figures mentioned below can be seen by selecting the appropriate chapter from this folder (Links to an external site.).  -->

 

## Chapter 1:  (Relevant for Units 1, 2, and 3)

**Section 1.1**: Living organisms have a common origin and share similarities

* Figure 1.1: The many faces of life
* Figures 1.2: Life's time line
* Figure 1.3: Membranes enclose the building blocks of life
* Figures 1.5: Biology is studied at many levels of organization
* Figure 1.7: Genetics developed as the study of discrete heritable traits
* **Figure 1.8: DNA is life's blueprint (F2!)**
* **Figure 1.9: Adaptations to the environment (F2!)**
* **Figure 1.10: The blueprint of life (F2!)**
* **Figure 1.11 Phylogenetic trees depict evolutionary relationships (F2!)**
* **Figure 1.12: The tree of life (F2!)**


##  Chapter 2: (Relevant for Units 1, 2, and 3)

* Figure 2.12: Hydrogen bonds can form between or within molecules
* Figure 2.13: Hydrophillic or hydrophobic
 

## Chapter 3:  (Relevant for Unit 1)

**Section 3.2. **

* Focal figures: 3.7 (F2!), 3.9 (F2!), 3.11 (F2!).  
* See also figures 3.13, 3.15 (F2!) & 3.16-middle panel .
 

## Chapter 4 - Nucleic acids and the origin of life:  (Relevant for Unit 1)

**Section 4.1: Nucleic acids are informational macromolecules**

* Focal figures 4.1 (F2!), 4.2 (F2!), 4.3a (F2!), 4.4 (F2!), 4.5 (F2!);
* Table 4.1 (F2!).  

**Section 4.3: The large molecules of life originated from small molecules**

* Focal figure 4.9

**Section 4.4**

## Chapter 5 - Cells: The working units of life  (Relevant for Unit 1)

**Section 5.3: Eukaryotic cells contain organelles**

* Subsection: "Ribosomes are factories for protein synthesis" (pg 88) (F2!)
* Subsection: "The endomembrane system is a group of interrelated organelles" (pg 92-93) (F2!)
* Focal Figure:  5.9 (F2!)

**Section 5.5: Eukaryotic cells evolved in several steps (endosymbiosis)**


## Chapter 8 (Relevant for Unit 1)

* Figure 8.9, 
* Figure 8.12
* Figure 8.16
* Figure 8.17
 

## Chapter 11 (Relevant for Unit 1)

* Section 11.5 (Meiosis; don't need to review the details of the figures).  
* Section 11.6 (Apoptosis) (F2!)
Section 11.7* (Cancer). 
See also Figure 11.2, Figure 11.8. 
 

## Chapter 12 (Relevant for Units 2, 3)

Section 12.2* "Alleles can produce multiple phenotypes" (pg 250 and 251)
Focal figure 12.9
Section 12.5 (ignore figure)
Section 12.6, especially subsection "Bacterial conjugation is controlled by plasmids*" (pg 262-263)
Focal Figure: 12.22*. 
Ignore figure 12.21.