# Lectures and Mini-quiz questions

Each week lecture material will be posted on Tuesday and Thursday mornings at 9:30 am. 


I will use the term "quizzes" because this is the term Canvas uses.

I will refer to these variously "mini-quizzes", "vocab builders", "concept builders" etc. to indicate their purpose.

These questions associated with lectures are always much easier than questions on the test and are mostly designed to reinforce vocab and basic graph interpretation.

Until the 1st mini-test all "quiz" questions remain open so that those who joined the class later can catch up. 
After the first test, mini-quiz questions will remain open until new lecture material is released. 

Therefore, mini-quiz questions opened on Tuesday mornings will close Thursday morning normally, and questions opened Thursday will close the next Tuesday.  

This schedule will be modified when there are tests.  To allow you time to review mini-quiz questions will close at 11:59 the night before the test.

Quizzes will be graded but you will have multiple attempts to take each quiz and opportunities to update your answers.   If a question only allows you to answer once please contact me and I will change the settings.

Questions will normally be set to show the key only after the question has closed.  Questions opened on the Tuesday prior to a test will be set to show the key after you have submitted your answer.  If this does not occur please contact me so I can change the settings.

As detailed elsewhere in the syllabus a portion of these mini-quiz questions will be dropped (e.g., to accommodate illness).

Readings to prepare for lectures will be released the preceding Friday at 9:00 am. 

Lecture videos will remain open for viewing except during tests.   