# Exam  Policies

## Number of exams & drop/replace policy.

1. There will be 3 mini-tests administered throughout the semester. 
1. No makeup exams will be given for any reason.
1. Your lowest scores of the  3 mini-test will be automatically dropped when grades are calculated at the end of the semester.  Prior to that it will be factored into your grade.
1. If you are unable to take a mini-test for ANY reason it will be counted zero.
1. If you miss just 1 test, that score will be automatically dropped as your lowest score when grades are calculated after the final.

1. If you take the final, your score on the final can replace your 2nd lowest score, if the final is higher.

Your grade will therefore be based on your 3 best scores; 1 of those 5 can include the final if you take it and score higher.



If you miss 2 tests, 1 will be dropped and the 2nd can be replaced by your score on the final, if you take it.
If you miss 3 tests, the 3rd zero will remain a zero.  If this occurs please contact your advisers to consider your options.
 

<!-- The final exam will be OPTIONAL(!) and can only benefit your grade. -->



## Exam length & format

NOTE: the following policies are provisional and may be adjusted as needed to optimize test length and how to implement the "buffer question" policy in Canvas.

* Exam will be scored out of 40 points.   However, there will be 41 points worth of questions on the test.  *
* Each test therefore will contain 1 buffer points that you can miss without harming your grade. 
* The maximum score on a mini-test will be capped at 40/40 If you get all 41 questions correct your score will be 100%. 
* No extra credit will be offered on tests; the maximum score on a test will be 100%.
 

## Test question formats

* Test questions will frequently be multiple choice.  Keyword: "frequently" - there will other types of questions too.
* Most tests will have more than one question requiring a numeric calculation.  You will be provided scratch paper for the exam.
* Other common forms of questions are fill in the blank, dropdowns, or matching.  This includes multiple fill in the blanks, multiple dropdowns, etc.  
* There will be NO True/False questions on tests.
* For fill in the blank questions spelling errors will result in 0 points.  No partial credit will be given.


<!-- * Some multiple-choice questions will likely be "select all correct answers."  For these questions, credit will only be given if you select ALL of the correct answers.  If you select an incorrect answer you will receive 0 points. -->

<!-- calculators -->


