# Final Exam Policies

The final exam will ...

1. Take place during finals week on the day scheduled by the University
1. Be online 
1. Be optional!
1. Follow the general format of the mini-tests, including having buffer question 
1. Potentially improve your grade


<!-- Yes, the final for this class is OPTIONAL - if you are happy with your test scores you will not have to take it. -->

The final exam is NOT one of the 6 unit "mini-tests" and NOT one of the five of those tests that count towards you grade.

**Note: **I do not hold office hours during finals week.

 

## Why take the final exam?

As noted previously, your lowest mini-test score will be automatically dropped. 

Your 2nd lowest test score can be replaced by your final exam, *if* your final exam score is higher. 

The final exam can therefore only benefit your score.

Questions on the final exam will be of similar difficulty as the 6 regular mini-tests.

I can only provide estimated grades prior to the exam. 

Information about the final exam schedule for the University can be found here:

https://www.registrar.pitt.edu/students/final-examsLinks to an external site.


What if I have more than one final exam on the same day?
If you have multiple finals scheduled for the same day see here:

https://www.registrar.pitt.edu/sites/default/files/pdf/final_guideline.pdf