# Key COVID informatio - Spring 2022

Key Covid and Flex@Pitt Information

This section of the syllabus summarizes key information related to our operation under the Flex@Pitt framework. Additional details and policies can be found under the relevant sections elsewhere in the syllabus.




Daily Course Operation

This course will be 100% online regardless of University operating posture. We will use pre-recorded lectures, online quizzes, assignments, and tests, live-streamed recitation sessions (also recorded), and instructor and undergraduate UTA office hours via Zoom. All assignments, quizzes and tests will be open for a window of at least 12 hours to allow completion. Assignments and quizzes will be open for at least 72 hours; final details will be posted on the first day of class.

Most course content will be presented asynchronously, and any material presented via live stream will be recorded and student participating asynchronously can view it and complete any exercises on their own time during the allotted window of time. Real-time participation in recitation will be optional and no points assigned to participation. Office hours will be held in person via Zoom and not recorded.

Course websites & technology

All course content will be released via Canvas and accessible regardless of the University's operating posture. A number of platforms will be used but all of them will be accessed from within Canvas. All lecture videos will be linked from Canvas to Panopto; videos from YouTube may occasionally be linked to Canvas also.  Most assignments, as well as exams, will be delivered using TopHat via links within Canvas. Students will be able to access a digital version of the textbook using Redshelf, or can opt-out of this program if they have their own cop of the book. Office hours will be held via Zoom. Most course materials will be in the form of Google Slides or Google Docs, which students can convert to Microsoft Word or PDF formats as needed.




Professor & UTA Office Hours

Regardless of University operating posture I will be available via Zoom from 1 to 2 PM on Tuesdays and Thursday. A Zoom link will be posted to Canvas to access these sessions. Any additions or changes to office hours scheduling will be announced via Canvas, with reminders during lectures. I will also be available at additional times throughout the week for 15 minute individual appointments. Please schedule via https://calendly.com/brouwern/15min . Registration via Calendly is not required for normal office hours, but is encouraged. You can always contact me at nlb24@pitt.edu.

Undergraduate Teaching Assistants will hold office hours in pairs via Zoom throughout the week. The schedule will be released by the first full week of class. UTA office hours may vary with University operating procedure, and any changes will be announced via Canvas.




COVID-19 safety:

In the midst of this pandemic, it is extremely important that you abide by public health regulations and University of Pittsburgh health standards and guidelines. These rules have been developed to protect the health and safety of all community members. For the most up-to-date information and guidance, please visit coronavirus.pitt.edu and check your Pitt email for updates before each class.

[Home | Modules ]